EdmureBlog/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^backend/', include('backend.urls')),
    url(r'^', include('web.urls')),
]

web/urls.py
from django.conf.urls import url
from .views import home
from .views import account

urlpatterns = [
    url(r'^jsonp.html$', account.jsonp),
    # url(r'^web/ariticle/(\d+).html$', home.ariticle),
    url(r'^login.html$', account.login),
    url(r'^logout.html$', account.logout),
    url(r'^register.html$', account.register),
    url(r'^check_code.html$', account.check_code),
    url(r'^all/(?P<article_type_id>\d+).html$', home.index, name='index'),
    url(r'^(?P<site>\w+).html$', home.home),
    url(r'^comment/$', home.comment),
    url(r'^(?P<site>\w+)/(?P<condition>((tag)|(date)|(category)))/(?P<val>\w+-*\w*).html$', home.filter),
    url(r'^(?P<site>\w+)/(?P<nid>\d+).html$', home.detail),
    url(r'^', home.index),
]

repository/models.py
from django.db import models
from django.core.exceptions import ValidationError
import datetime

class UserInfo(models.Model):
    """
    用户表
    """
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    email = models.EmailField(verbose_name='邮箱', unique=True)
    avatar = models.ImageField(verbose_name='头像',)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    fans = models.ManyToManyField(verbose_name='粉丝们',
                                  to='UserInfo',
                                  through='UserFans',
                                  related_name='f',
                                  through_fields=('user', 'follower'))


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客前缀', max_length=32, unique=True)
    type_choices = [
        (0, "默认主题"),
        (1, "红色主题"),
        (2, "绿色主题"),
        (3, "蓝色主题"),
    ]
    # theme = fields.IntegerField(choices=type_choices, default=0)
    theme = models.IntegerField(verbose_name='博客主题', default=0, choices=type_choices)
    user = models.OneToOneField(to='UserInfo', to_field='nid')


class UserFans(models.Model):
    """
    互粉关系表
    """
    user = models.ForeignKey(verbose_name='博主', to='UserInfo', to_field='nid', related_name='users')
    follower = models.ForeignKey(verbose_name='粉丝', to='UserInfo', to_field='nid', related_name='followers')

    class Meta:
        unique_together = [
            ('user', 'follower'),
        ]


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)

    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')


class ArticleDetail(models.Model):
    """
    文章详细表
    """
    content = models.TextField(verbose_name='文章内容', )

    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid')


class UpDown(models.Model):
    """
    文章顶或踩
    """
    article = models.ForeignKey(verbose_name='文章', to='Article', to_field='nid')
    user = models.ForeignKey(verbose_name='赞或踩用户', to='UserInfo', to_field='nid')
    up = models.BooleanField(verbose_name='是否赞')

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]

# 1 楼下sb 程毅强 11         None
# 2 是的 马良    11          None
# 3 说的太对了 yanhang    11  1
# 4 2楼是sb   程毅强 11      None
# 5 你说的都对   程毅强 11      4
class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True, )
    reply = models.ForeignKey(verbose_name='回复评论', to='self', related_name='back', null=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid')
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', related_name='comm')


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', default=2)


class Article(models.Model):
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题', max_length=128)
    summary = models.CharField(verbose_name='文章简介', max_length=255)
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    pub_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')
    category = models.ForeignKey(verbose_name='文章类型', to='Category', to_field='nid', null=True)
    type_choices = [
        (1, "Python"),
        (2, "Linux"),
        (3, "Docker"),
        (4, "GoLang"),
        (5, "OpenStack"),
    ]
    article_type_id = models.IntegerField(choices=type_choices, default=None)
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )
    status_choices = [('draft',u"草稿"),
                      ('published',u"已发布"),
                      ('hidden',u"隐藏"),
                      ]
    status = models.CharField(choices=status_choices,default='published',max_length=32)
    def __str__(self):
        return self.title
    def clean(self):
        # Don't allow draft entries to have a pub_date.
        if self.status == 'draft' and self.pub_date is not None:
            raise ValidationError(('Draft entries may not have a publication date.'))
        # Set the pub_date for published items if it hasn't been set already.
        if self.status == 'published' and self.pub_date is None:
            self.pub_date = datetime.date.today()

class Article2Tag(models.Model):
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid')
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid')

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

web/views/home.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.shortcuts import redirect
from repository import models
from utils.pagination import Pagination
from django.urls import reverse
from ..forms.comment import CommentForm


def index(request, *args, **kwargs):
    """
    博客首页，展示全部博文
    :param request:
    :return:
    """
    article_type_list = models.Article.type_choices
    if kwargs:
        article_type_id = int(kwargs['article_type_id'])
        base_url = reverse('index', kwargs=kwargs)
    else:
        article_type_id = None
        base_url = '/'
    kwargs['status'] = 'published'
    data_count = article_list = models.Article.objects.filter(**kwargs).count()
    page_obj = Pagination(request.GET.get('p'),data_count)
    article_list = models.Article.objects.filter(**kwargs).order_by('-nid')[page_obj.start:page_obj.end]
    page_str = page_obj.page_str(base_url)
    top7 = models.Article.objects.order_by('comment_count')[:7]
    print(top7)
    return render(
        request,
        'index.html',
        {
            'article_list': article_list,
            'article_type_id': article_type_id,
            'article_type_list': article_type_list,
            'page_str': page_str,
            'top7': top7,
        }
    )


def home(request, site):
    """
    博主个人首页
    :param request:
    :param site: 博主的网站后缀如：http://xxx.com/wupeiqi.html
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    # date_format(create_time,"%Y-%m")
    date_list = models.Article.objects.raw(
        #'select nid, count(nid) as num,date_format("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')
        'select nid, count(nid) as num,date_format(pub_date,"%%Y-%%m") as ctime from repository_article group by date_format(pub_date,"%%Y-%%m")')

    for item in date_list:
        print(item.nid,item.num,item.ctime)
    article_list = models.Article.objects.filter(blog=blog,status='published').order_by('-nid').all()

    return render(
        request,
        'home.html',
        {
            'blog': blog,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
            'article_list': article_list
        }
    )


def filter(request, site, condition, val):
    """
    分类显示
    :param request:
    :param site:
    :param condition:
    :param val:
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        #'select nid, count(nid) as num,strftime("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')
        'select nid, count(nid) as num,date_format(pub_date,"%%Y-%%m") as ctime from repository_article group by date_format(pub_date,"%%Y-%%m")')

    template_name = "home_summary_list.html"
    if condition == 'tag':
        template_name = "home_title_list.html"
        article_list = models.Article.objects.filter(tags=val, blog=blog,status='published').all()
    elif condition == 'category':
        article_list = models.Article.objects.filter(category_id=val, blog=blog,status='published').all()
    elif condition == 'date':
        article_list = models.Article.objects.filter(blog=blog,status='published').extra(
        where=['date_format(pub_date,"%%Y-%%m")=%s'], params=[val, ]).all()

        #article_list = models.Article.objects.filter(blog=blog).extra(
        #    where=['strftime("%%Y-%%m",create_time)=%s'], params=[val, ]).all()
        # select * from article where strftime("%Y-%m",create_time)=2017-02
    else:
        article_list = []

    return render(
        request,
        template_name,
        {
            'blog': blog,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
            'article_list': article_list
        }
    )


def detail(request, site, nid):
    """
    博文详细页
    :param request:
    :param site:
    :param nid:
    :return:
    
    """
    if request.method == "GET":
        blog = models.Blog.objects.filter(site=site).select_related('user').first()
        tag_list = models.Tag.objects.filter(blog=blog)
        category_list = models.Category.objects.filter(blog=blog)
        date_list = models.Article.objects.raw(
            'select nid, count(nid) as num,date_format(pub_date,"%%Y-%%m") as ctime from repository_article group by date_format(pub_date,"%%Y-%%m")')

        article = models.Article.objects.filter(blog=blog, nid=nid, status='published').select_related('category', 'articledetail').first()
        comment_list = models.Comment.objects.filter(article=article).select_related('reply').all()

        try:
            user_id = request.session.get('user_info').get('nid')
        except:
            user_id = ''
        return render(
            request,
            'home_detail.html',
            {
                'blog': blog,
                'article': article,
                'comment_list': comment_list,
                'tag_list': tag_list,
                'category_list': category_list,
                'date_list': date_list,
                'article_id': nid,
                'user_id': user_id,
            }

        )
    elif request.method == 'POST':
        data = {}
        # print(request.POST)
        data['content'] = request.POST.get('content')
        data['article_id'] = request.POST.get('article')
        try:
            user_id = request.session.get('user_info').get('nid')
            data['user_id'] = user_id
        except:
            return HttpResponse('nologin')
        if request.POST.get('reply'):
            data['reply_id'] = request.POST.get('reply')
        # print(data)
        # print(data)
        from django.db.models import F
        # models.Tb1.objects.update(num=F('num')+1)
        models.Comment.objects.create(**data)
        # sql = 'update repository_article set comment_count=2 where nid = {}'.format(request.POST.get('article'))
        # print(sql)
        models.Article.objects.filter(nid=data['article_id']).update(comment_count=F('comment_count')+1)
        return HttpResponse('ok')



def comment(request):
    '''
    文章首页点击显示评论
    :param request: 
    :return: 
    '''
    import datetime
    nid = request.POST.get('nid')
    # data = models.Comment.objects.extra(where=['article_id=%s'], params=[nid]).values()
    data = models.Comment.objects.filter(article__nid=nid).values('nid',
                                                                  'content',
                                                                  'create_time',
                                                                  'reply_id',
                                                                  'article_id',
                                                                  'user__username')
    # # print(data[2].user.username)
    # print(data)
    # data = models.Comment.objects.filter(article__nid=nid).select_related('user')
    import json
    from datetime import date
    from datetime import datetime

    class JsonCustomEncoder(json.JSONEncoder):

        def default(self, field):

            if isinstance(field, datetime):
                return field.strftime('%Y-%m-%d %H:%M:%S')
            elif isinstance(field, date):
                return field.strftime('%Y-%m-%d')
            else:
                return json.JSONEncoder.default(self, field)

    dd = json.dumps(list(data), cls=JsonCustomEncoder)



    # from django.core import serializers
    # dd = serializers.serialize("json", models.Comment.objects.filter(article__nid=nid),
    #                            fields=('user', 'ussaf',))
    print(dd)
    return HttpResponse(dd)

templates/backend_article.html
{% extends 'backend_layout.html' %}
{% load search %}
{% block css %}
<style>
    .conditions a{
        display: inline-block;
        padding: 2px 5px;
        margin-left: 5px;
    }
    .conditions a.active{
        background-color: #b35215;
        color: #ffffff;
    }
</style>
{% endblock %}
{% block conent %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">文章列表</li>
    </ol>
    <div>

        <div style="border: 1px dashed #dddddd;padding: 8px;border-left: 3px solid #337ab7;">
            <i class="fa fa-search" aria-hidden="true"></i> 搜索条件
        </div>
        <div style="padding: 10px">
            <div class="conditions row clearfix" style="margin: 0;padding: 8px 0;">
                <div class="col-xs-1" style="text-align: right">
                    {% category_all arg_dict %}
                </div>
                <div class="col-xs-11">
                    {% category_combine category_list arg_dict %}
                </div>
            </div>
            <div class="conditions row clearfix" style="margin: 0;padding: 8px 0;">
                <div class="col-xs-1" style="text-align: right">
                    {% article_type_all arg_dict %}
                </div>
                <div class="col-xs-11">
                    {% article_type_combine type_list arg_dict %}
                </div>
            </div>
        </div>
        <div class="clearfix"
             style="height: 36px;line-height: 35px;padding: 0 15px;border-top: 1px solid #dddddd;background-color: #f1f0f0">
            <i class="fa fa-table" aria-hidden="true"></i>
            搜索文章({{ data_count }}篇)
            <a target="_self" href="/backend/add-article.html" class="right"
               style="display: inline-block;padding:0 10px;background-color: #428bca;color: #ffffff;">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                创建新文章
            </a>
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>文章标题</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in result %}
                <tr nid="{{ row.nid }}">
                    <td><a href="/{{ row.blog.site }}/{{ row.nid }}.html">{{ row.title }}</a></td>
                    <td><a href="/backend/edit-article-{{ row.nid }}.html">{{ row.status }}</a></td>
                    <td>
                        <a class="btn btn-danger btn-xs" href="/backend/delete-article-{{ row.nid }}.html" 
                                 onclick="if(confirm('确定删除？')==false)return false;">
                            <i class="fa fa-times" aria-hidden="true"></i>
                            删除
                        </a>
                        |
                        <a class="btn btn-primary btn-xs" href="/backend/edit-article-{{ row.nid }}.html">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            编辑
                        </a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
               {{ page_str }}
            </ul>
        </div>
    </div>


{% endblock %}

{% block js %}

{% endblock %}

templates/backend_category.html
{% extends 'backend_layout.html' %}
{% block css %}

{% endblock %}
{% block conent %}
    <ol class="breadcrumb">
        <li><a href="#">分类管理</a></li>
        <li class="active">分类列表</li>
    </ol>
    <div>
        <div class="row" style="padding: 20px 5px;">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="col-xs-12">


                    <div class="form-group">
                        <label class="col-xs-1 control-label">分类名称</label>

                        <div class="col-xs-3">
                            <input type="text" class="form-control" id="nickname" placeholder="请输入分类名称" name="title">
                            <input type="number" name="func" value=0 class="hidden">
                        </div>
                        <div class="col-xs-3">
                            <input type="submit" class="btn btn-primary" value="添 加">
                        </div>
                    </div>


                    {% if err %}
                        <div class="form-group">
                        <label class="col-xs-1 control-label">警告</label>
                        <div class="col-xs-3">
                            <span style="background-color: red" class="btn">{{ err }}</span>
                        </div>
                        </div>
                        {% endif %}


                </div>
            </form>
        </div>

        <div style="height: 35px;background-color: #f5f5f5;line-height: 35px;padding: 0 15px;">
            <i class="fa fa-table" aria-hidden="true"></i>
            标签列表
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>分类</th>
                <th>文章个数</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
{#            <tr>#}
{#                <td>妹子</td>#}
{#                <td>10</td>#}
{#                <td>#}
{#                    <a class="btn btn-danger btn-xs">#}
{#                        <i class="fa fa-times" aria-hidden="true"></i>#}
{#                        删除#}
{#                    </a>#}
{#                    |#}
{#                    <a class="btn btn-primary btn-xs">#}
{#                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>#}
{#                        编辑#}
{#                    </a>#}
{#                </td>#}
{#            </tr>#}
{#            <tr>#}
{#                <td>Coding</td>#}
{#                <td>8</td>#}
{#                <td>#}
{#                    <a class="btn btn-danger btn-xs">#}
{#                        <i class="fa fa-times" aria-hidden="true"></i>#}
{#                        删除#}
{#                    </a>#}
{#                    |#}
{#                    <a class="btn btn-primary btn-xs">#}
{#                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>#}
{#                        编辑#}
{#                    </a>#}
{#                </td>#}
{#            </tr>#}
{#            <tr>#}
{#                <td>旅行</td>#}
{#                <td>10</td>#}
{#                <td>#}
{#                    <a class="btn btn-danger btn-xs">#}
{#                        <i class="fa fa-times" aria-hidden="true"></i>#}
{#                        删除#}
{#                    </a>#}
{#                    |#}
{#                    <a class="btn btn-primary btn-xs">#}
{#                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>#}
{#                        编辑#}
{#                    </a>#}
{#                </td>#}
{#            </tr>#}
                        {% for i in obj %}
                <tr nid="{{ i.nid }}">
                <td><input style="border: 0; background: none" type="text" disabled value="{{ i.title }}"><span class="hidden">{{ i.title }}</span></td>
                <td>{{ i.article_set.all.count }}</td>
                <td>
                    <a class="btn btn-danger btn-xs">
                        <i class="fa fa-times" aria-hidden="true"></i>
                        删除
                    </a>
                    |
                    <a class="btn btn-primary btn-xs">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        编辑
                    </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
              {{ page_str }}
            </ul>
        </div>
    </div>


{% endblock %}

{% block js %}
<script>
// 删除按钮
$(".btn-danger").each(function () {
    $(this).click(function () {
        var t = $(this).parent().parent();
        console.log(t.attr('nid'));
        $.ajax({
            headers:{'x-CSRFtoken': $.cookie('csrftoken')},
            type:"POST",
            data: {'func': '1', 'nid': t.attr('nid')},
            success: function (data, a1, a2) {
                if(data == 'ok'){
                    t.remove();
                }else {
                    alert(data)
                }
            }
        })
    })
});

// 编辑按钮
$('.btn-primary').each(function () {
    $(this).click(function () {
        var t = $(this).parent().prev().prev();
        var a = $(this);
        if(a.text() != '确定'){
            t.children('input').removeAttr('disabled').focus();
            a.text('确定')
        }else {
{#            console.log(t.children('input').val());#}
{#            console.log(t.children('span').text());#}
            if (t.children('input').val()!=t.children('span').text()){
                $.ajax({
                    headers:{'x-CSRFtoken': $.cookie('csrftoken')},
                    type:"POST",
                    data: {
                        'func': '2',
                        'nid': t.parent().attr('nid'),
                        'title': t.children('input').val()
                    },
                    success: function (data, a1, a2) {
                        if(data == 'ok'){
                            var l = document.createElement('li');
                            l.className = "fa fa-pencil-square-o";
                            a.text('编辑').prepend(l);
                            t.children('input').attr('disabled', true);
                            t.children('span').text(t.children('input').val());
                        }else {
                            alert(data)
                        }
                    }
                })
            }else {
                var l = document.createElement('li');
                l.className = "fa fa-pencil-square-o";
                a.text('编辑').prepend(l);
                t.children().attr('disabled', true)
            }
        }
    })
})

</script>
{% endblock %}

templates/backend_edit_article.html
{% extends 'backend_layout.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/plugins/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content {
            width: 100%;
            min-height: 500px;
        }
    </style>
{% endblock %}

{% block conent %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">修改文章</li>
    </ol>
    <div style="padding: 5px 8px;">
        <form method="POST" action="/backend/edit-article-{{ nid }}.html">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="summary">简介 <span>{{ form.summary.errors.0 }}</span></label>
                {{ form.summary }}
            </div>
            <div class="form-group">
                <label for="content">内容 <span>{{ form.content.errors.0 }}</span></label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label>类型 <span>{{ form.article_type.errors.0 }}</span></label>

                <div>
                    {{ form.article_type_id }}
                </div>

            </div>
            <div class="form-group">
                <label>分类 <span>{{ form.category_id.errors.0 }}</span></label>

                <div>
                    {{ form.category_id }}
                </div>
            </div>
            <div class="form-group">
                <label>标签 <span>{{ form.tags.errors.0 }}</span></label>
                <div>
                    {{ form.tags }}
                </div>
            </div>

            <div class="form-group">
                <label>状态 <span>{{ form.status.errors.0 }}</span></label>
                <div>
                    {{ form.status }}
                </div>
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保 存">
            </div>
        </form>
    </div>


{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>
        KindEditor.ready(function (K) {
            var editor = K.create('textarea[name="content"]', {
                resizeType: 1
            });
        });
    </script>
{% endblock %}

templates/backend_index.html
{% extends 'backend_layout.html' %}
{% block css %}

{% endblock %}
{% block conent %}
   <h1>欢迎登陆：{{ request.session.user_info.nickname }}</h1>
{% endblock %}

{% block js %}

{% endblock %}

templates/home_layout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/edmure.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
    <link rel="stylesheet" href="/static/css/row-avatar.css"/>
    <link rel="stylesheet" href="/static/css/theme/{{ blog.theme }}.css"/>
    {% block css %}{% endblock %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap/js/bootstrap.js"></script>
</head>

<body>

{% load count_article %}

<div class="pg-header">
    <div class="title">{{ blog.title }}</div>
    <div class="menu-list">
        <a class="menu-item" href="/">首页</a>
        <a class="menu-item" href="/{{ blog.site }}.html">个人首页</a>
        <a class="menu-item" href="/backend/index.html">管理</a>
    </div>
</div>
<div class="pg-body">
    <div class="body-menu">
        <div class="notice">
            <div class="notice-header">公告</div>
            <div class="notice-body">
                <ul>
                    <li>昵称：{{ blog.user.nickname }}</li>
                    <li>粉丝：{{ blog.user.fans.count }}</li>
                    <li>关注：{{ blog.user.f.count }}</li>
                    <li>邮箱：{{ blog.user.email }}</li>
                </ul>
                <div class="memo">
                    信因果，学智慧，修自身。
                </div>
            </div>
        </div>
        <div class="tags">
            <div class="tags-header">标签</div>
            <div class="tags-body">
                <ul>
                    {% for tag in tag_list %}
{#                        <li><a href="/{{ blog.site }}/tag/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>#}
                        <li><a href="/{{ blog.site }}/tag/{{ tag.nid }}.html">{{ tag.title }}({% published tag.article_set %})</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="types">
            <div class="types-header">分类</div>
            <div class="types-body">
                <ul>
                    {% for tag in category_list %}
                        <li><a href="/{{ blog.site }}/category/{{ tag.nid }}.html">{{ tag.title }}({% published tag.article_set %})</a></li>
                    {% endfor %}
                </ul>

            </div>
        </div>
        <div class="dates">
            <div class="dates-header">时间</div>
            <div class="dates-body">
                <ul>
                    {% for tag in date_list %}
                        <li><a href="/{{ blog.site }}/date/{{ tag.ctime }}.html">{{ tag.ctime}}({{ tag.num}})</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">
        {% block content %}{% endblock %}
    </div>
</div>
    {% block js %}{% endblock %}
</body>
</html>